In [4]:
import pandas as pd
import numpy as np
df = pd.DataFrame(np.random.randn(100, 2), columns=['A','B'])
df

           A         B
0  -1.125045 -0.483409
1  -0.938163 -0.938230
2  -0.786639 -0.354908
3   0.057680  0.780618
4  -1.552638 -0.793968
5   1.797579 -0.858343
6   2.485739  1.043662
7  -1.910197  0.882532
8   1.048265  1.309782
9  -1.550019 -0.984409
10  0.465058 -0.193407
11  1.672525 -1.574265
12 -1.488166 -0.275860
13  0.526016 -1.339838
14  0.081901 -1.262409
15  1.163214  1.004157
16  0.677524  0.751326
17  0.708705  1.150351
18 -0.878038  0.770110
19  1.032895  0.937925
20 -0.376133  1.214961
21 -1.014094 -1.278408
22  0.831146 -0.004973
23  0.964057  0.707149
24  0.668902 -0.031821
25  0.809970 -0.122453
26 -0.118526 -0.604414
27  2.861770  0.804984
28 -0.584773  0.940563
29  1.444139 -0.206933
..       ...       ...
70  0.442995  1.073292
71 -0.085350  0.234248
72  1.056282 -0.436473
73 -0.844001 -0.149475
74  1.320638  1.049127
75 -0.192583  1.705012
76  2.126020 -0.664933
77  0.445812  0.352108
78 -0.230803  0.539163
79 -1.965974 -1.690744
80  1.599803  0.741662
81  0.678118  1.088133
82 -0.248672  0.671722
83 -0.256164  1.078139
84  2.152748 -1.617708
85 -0.469145 -1.401613
86 -0.943344  0.032929
87  0.821996  1.335366
88 -0.356415 -0.033445
89 -0.193972 -0.911758
90 -0.557639  0.851526
91  0.167004  0.835275
92 -1.995778 -1.365451
93  0.150026 -0.818328
94  0.998247 -1.529968
95 -1.033859  1.112170
96 -0.315896 -1.612296
97 -0.534942  0.724738
98  0.758812  0.088879
99  0.135591 -1.288286

[100 rows x 2 columns]